<a href="https://colab.research.google.com/github/Nagah1/Sales_insights/blob/main/Untitled24.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv('/content/Sales_April_2019.csv')

In [ ]:
data

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001"
1,NaN,NaN,NaN,NaN,NaN,NaN
2,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215"
3,176560,Google Phone,1,600,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
4,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
...,...,...,...,...,...,...
18378,194090,Google Phone,1,600,04/08/19 17:11,"177 Jackson St, Los Angeles, CA 90001"
18379,194091,AA Batteries (4-pack),1,3.84,04/15/19 16:02,"311 Forest St, Austin, TX 73301"
18380,194092,AAA Batteries (4-pack),2,2.99,04/28/19 14:36,"347 Sunset St, San Francisco, CA 94016"
18381,194093,AA Batteries (4-pack),1,3.84,04/14/19 15:09,"835 Lake St, Portland, OR 97035"
18382,194094,Lightning Charging Cable,1,14.95,04/18/19 11:08,"354 North St, Boston, MA 02215"

In [ ]:
data.dropna()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001"
2,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215"
3,176560,Google Phone,1,600,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
4,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
5,176561,Wired Headphones,1,11.99,04/30/19 09:27,"333 8th St, Los Angeles, CA 90001"
...,...,...,...,...,...,...
18378,194090,Google Phone,1,600,04/08/19 17:11,"177 Jackson St, Los Angeles, CA 90001"
18379,194091,AA Batteries (4-pack),1,3.84,04/15/19 16:02,"311 Forest St, Austin, TX 73301"
18380,194092,AAA Batteries (4-pack),2,2.99,04/28/19 14:36,"347 Sunset St, San Francisco, CA 94016"
18381,194093,AA Batteries (4-pack),1,3.84,04/14/19 15:09,"835 Lake St, Portland, OR 97035"
18382,194094,Lightning Charging Cable,1,14.95,04/18/19 11:08,"354 North St, Boston, MA 02215"

In [ ]:
data.drop_duplicates()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001"
1,NaN,NaN,NaN,NaN,NaN,NaN
2,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215"
3,176560,Google Phone,1,600,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
4,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
...,...,...,...,...,...,...
18378,194090,Google Phone,1,600,04/08/19 17:11,"177 Jackson St, Los Angeles, CA 90001"
18379,194091,AA Batteries (4-pack),1,3.84,04/15/19 16:02,"311 Forest St, Austin, TX 73301"
18380,194092,AAA Batteries (4-pack),2,2.99,04/28/19 14:36,"347 Sunset St, San Francisco, CA 94016"
18381,194093,AA Batteries (4-pack),1,3.84,04/14/19 15:09,"835 Lake St, Portland, OR 97035"
18382,194094,Lightning Charging Cable,1,14.95,04/18/19 11:08,"354 North St, Boston, MA 02215"

In [ ]:
data.dropna()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001"
2,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215"
3,176560,Google Phone,1,600,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
4,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
5,176561,Wired Headphones,1,11.99,04/30/19 09:27,"333 8th St, Los Angeles, CA 90001"
...,...,...,...,...,...,...
18378,194090,Google Phone,1,600,04/08/19 17:11,"177 Jackson St, Los Angeles, CA 90001"
18379,194091,AA Batteries (4-pack),1,3.84,04/15/19 16:02,"311 Forest St, Austin, TX 73301"
18380,194092,AAA Batteries (4-pack),2,2.99,04/28/19 14:36,"347 Sunset St, San Francisco, CA 94016"
18381,194093,AA Batteries (4-pack),1,3.84,04/14/19 15:09,"835 Lake St, Portland, OR 97035"
18382,194094,Lightning Charging Cable,1,14.95,04/18/19 11:08,"354 North St, Boston, MA 02215"

In [ ]:
data.describe()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
count,18324,18324,18324,18324,18324,18324
unique,17538,20,8,19,13584,17120
top,Order ID,Lightning Charging Cable,1,14.95,Order Date,Purchase Address
freq,35,2201,16558,2201,35,35

In [ ]:
data.isnull().sum()

Order ID            59
Product             59
Quantity Ordered    59
Price Each          59
Order Date          59
Purchase Address    59
dtype: int64

In [ ]:
data.dropna()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001"
2,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215"
3,176560,Google Phone,1,600,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
4,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
5,176561,Wired Headphones,1,11.99,04/30/19 09:27,"333 8th St, Los Angeles, CA 90001"
...,...,...,...,...,...,...
18378,194090,Google Phone,1,600,04/08/19 17:11,"177 Jackson St, Los Angeles, CA 90001"
18379,194091,AA Batteries (4-pack),1,3.84,04/15/19 16:02,"311 Forest St, Austin, TX 73301"
18380,194092,AAA Batteries (4-pack),2,2.99,04/28/19 14:36,"347 Sunset St, San Francisco, CA 94016"
18381,194093,AA Batteries (4-pack),1,3.84,04/14/19 15:09,"835 Lake St, Portland, OR 97035"
18382,194094,Lightning Charging Cable,1,14.95,04/18/19 11:08,"354 North St, Boston, MA 02215"

In [ ]:
data = data.dropna()

In [ ]:
data

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001"
2,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215"
3,176560,Google Phone,1,600,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
4,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
5,176561,Wired Headphones,1,11.99,04/30/19 09:27,"333 8th St, Los Angeles, CA 90001"
...,...,...,...,...,...,...
18378,194090,Google Phone,1,600,04/08/19 17:11,"177 Jackson St, Los Angeles, CA 90001"
18379,194091,AA Batteries (4-pack),1,3.84,04/15/19 16:02,"311 Forest St, Austin, TX 73301"
18380,194092,AAA Batteries (4-pack),2,2.99,04/28/19 14:36,"347 Sunset St, San Francisco, CA 94016"
18381,194093,AA Batteries (4-pack),1,3.84,04/14/19 15:09,"835 Lake St, Portland, OR 97035"
18382,194094,Lightning Charging Cable,1,14.95,04/18/19 11:08,"354 North St, Boston, MA 02215"

In [ ]:
data.isnull().sum()

Order ID            0
Product             0
Quantity Ordered    0
Price Each          0
Order Date          0
Purchase Address    0
dtype: int64

In [ ]:
data = data.drop_duplicates()

In [ ]:
data

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001"
2,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215"
3,176560,Google Phone,1,600,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
4,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
5,176561,Wired Headphones,1,11.99,04/30/19 09:27,"333 8th St, Los Angeles, CA 90001"
...,...,...,...,...,...,...
18378,194090,Google Phone,1,600,04/08/19 17:11,"177 Jackson St, Los Angeles, CA 90001"
18379,194091,AA Batteries (4-pack),1,3.84,04/15/19 16:02,"311 Forest St, Austin, TX 73301"
18380,194092,AAA Batteries (4-pack),2,2.99,04/28/19 14:36,"347 Sunset St, San Francisco, CA 94016"
18381,194093,AA Batteries (4-pack),1,3.84,04/14/19 15:09,"835 Lake St, Portland, OR 97035"
18382,194094,Lightning Charging Cable,1,14.95,04/18/19 11:08,"354 North St, Boston, MA 02215"

In [ ]:
data.to_csv('april_1')

In [ ]:
data2 = pd.read_csv('/content/april_1')

In [ ]:
data2

,Unnamed: 0,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001"
1,2,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215"
2,3,176560,Google Phone,1,600,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
3,4,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
4,5,176561,Wired Headphones,1,11.99,04/30/19 09:27,"333 8th St, Los Angeles, CA 90001"
...,...,...,...,...,...,...,...
18263,18378,194090,Google Phone,1,600,04/08/19 17:11,"177 Jackson St, Los Angeles, CA 90001"
18264,18379,194091,AA Batteries (4-pack),1,3.84,04/15/19 16:02,"311 Forest St, Austin, TX 73301"
18265,18380,194092,AAA Batteries (4-pack),2,2.99,04/28/19 14:36,"347 Sunset St, San Francisco, CA 94016"
18266,18381,194093,AA Batteries (4-pack),1,3.84,04/14/19 15:09,"835 Lake St, Portland, OR 97035"
18267,18382,194094,Lightning Charging Cable,1,14.95,04/18/19 11:08,"354 North St, Boston, MA 02215"

In [ ]:
new = pd.read_csv('/content/Sales_May_2019.csv.....csv')

In [ ]:
new

,Order ID,Len,Product,Quantity Ordered,Price Each,Total,Month,Order Date,Purchase Address,Country,State,number of state
0,194095,1,Wired Headphones,1,11.99,11.99,May,5/16/2019 17:14,669 2nd St,New York City,NY,10001
1,194096,1,AA Batteries (4-pack),1,3.84,3.84,May,5/19/2019 14:43,844 Walnut St,Dallas,TX,75001
2,194097,1,27in FHD Monitor,1,149.99,149.99,May,5/24/2019 11:36,164 Madison St,New York City,NY,10001
3,194098,1,Wired Headphones,1,11.99,11.99,May,5/2/2019 20:40,622 Meadow St,Dallas,TX,75001
4,194099,1,AAA Batteries (4-pack),2,2.99,5.98,May,5/11/2019 22:55,17 Church St,Seattle,WA,98101
...,...,...,...,...,...,...,...,...,...,...,...,...
16497,209916,1,Bose SoundSport Headphones,1,99.99,99.99,May,5/8/2019 19:15,235 Center St,Seattle,WA,98101
16498,209917,1,Wired Headphones,1,11.99,11.99,May,5/24/2019 22:02,926 9th St,San Francisco,CA,94016
16499,209918,1,AAA Batteries (4-pack),2,2.99,5.98,May,5/24/2019 17:44,868 Hickory St,Boston,MA,2215
16500,209919,1,USB-C Charging Cable,1,11.95,11.95,May,5/4/2019 12:46,204 Adams St,Seattle,WA,98101
16501,209920,1,ThinkPad Laptop,1,999.99,999.99,May,5/18/2019 23:07,43 5th St,Atlanta,GA,30301

In [ ]:
new.isnull().sum()

Order ID            0
Len                 0
Product             0
Quantity Ordered    0
Price Each          0
Total               0
Month               0
Order Date          0
Purchase Address    0
Country             0
State               0
number of state     0
dtype: int64

In [ ]:
new.drop_duplicates()

,Order ID,Len,Product,Quantity Ordered,Price Each,Total,Month,Order Date,Purchase Address,Country,State,number of state
0,194095,1,Wired Headphones,1,11.99,11.99,May,5/16/2019 17:14,669 2nd St,New York City,NY,10001
1,194096,1,AA Batteries (4-pack),1,3.84,3.84,May,5/19/2019 14:43,844 Walnut St,Dallas,TX,75001
2,194097,1,27in FHD Monitor,1,149.99,149.99,May,5/24/2019 11:36,164 Madison St,New York City,NY,10001
3,194098,1,Wired Headphones,1,11.99,11.99,May,5/2/2019 20:40,622 Meadow St,Dallas,TX,75001
4,194099,1,AAA Batteries (4-pack),2,2.99,5.98,May,5/11/2019 22:55,17 Church St,Seattle,WA,98101
...,...,...,...,...,...,...,...,...,...,...,...,...
16497,209916,1,Bose SoundSport Headphones,1,99.99,99.99,May,5/8/2019 19:15,235 Center St,Seattle,WA,98101
16498,209917,1,Wired Headphones,1,11.99,11.99,May,5/24/2019 22:02,926 9th St,San Francisco,CA,94016
16499,209918,1,AAA Batteries (4-pack),2,2.99,5.98,May,5/24/2019 17:44,868 Hickory St,Boston,MA,2215
16500,209919,1,USB-C Charging Cable,1,11.95,11.95,May,5/4/2019 12:46,204 Adams St,Seattle,WA,98101
16501,209920,1,ThinkPad Laptop,1,999.99,999.99,May,5/18/2019 23:07,43 5th St,Atlanta,GA,30301

In [ ]:
new.to_excel

<bound method NDFrame.to_excel of        Order ID  Len                     Product  Quantity Ordered  \
0        194095    1            Wired Headphones                 1
1        194096    1       AA Batteries (4-pack)                 1
2        194097    1            27in FHD Monitor                 1
3        194098    1            Wired Headphones                 1
4        194099    1      AAA Batteries (4-pack)                 2
...         ...  ...                         ...               ...
16497    209916    1  Bose SoundSport Headphones                 1
16498    209917    1            Wired Headphones                 1
16499    209918    1      AAA Batteries (4-pack)                 2
16500    209919    1        USB-C Charging Cable                 1
16501    209920    1             ThinkPad Laptop                 1

       Price Each   Total Month       Order Date Purchase Address  \
0           11.99   11.99   May  5/16/2019 17:14       669 2nd St
1            3.84    3.84   May  5/19/2019 14:43    844 Walnut St
2          149.99  149.99   May  5/24/2019 11:36   164 Madison St
3           11.99   11.99   May   5/2/2019 20:40    622 Meadow St
4            2.99    5.98   May  5/11/2019 22:55     17 Church St
...           ...     ...   ...              ...              ...
16497       99.99   99.99   May   5/8/2019 19:15    235 Center St
16498       11.99   11.99   May  5/24/2019 22:02       926 9th St
16499        2.99    5.98   May  5/24/2019 17:44   868 Hickory St
16500       11.95   11.95   May   5/4/2019 12:46     204 Adams St
16501      999.99  999.99   May  5/18/2019 23:07        43 5th St

              Country State  number of state
0       New York City    NY            10001
1              Dallas    TX            75001
2       New York City    NY            10001
3              Dallas    TX            75001
4             Seattle    WA            98101
...               ...   ...              ...
16497         Seattle    WA            98101
16498   San Francisco    CA            94016
16499          Boston    MA             2215
16500         Seattle    WA            98101
16501         Atlanta    GA            30301

[16502 rows x 12 columns]>

In [ ]:
new.to_csv('new_may')

In [ ]:
feb = pd.read_csv('/content/Sales_February_2019.csv')

In [ ]:
feb

,Order ID,Product,lenth,Quantity Ordered,Price Each,Total of Amount,Month,Order Date,Purchase Address,Country,State,number of state
0,160509,AAA Batteries (4-pack),1,2,2.99,5.98,February,2/1/2019 1:51,597 Chestnut St,Austin,TX,73301
1,156889,USB-C Charging Cable,1,1,11.95,11.95,February,2/1/2019 4:25,703 9th St,Los Angeles,CA,90001
2,156342,USB-C Charging Cable,1,1,11.95,11.95,February,2/1/2019 5:39,556 Cherry St,San Francisco,CA,94016
3,159193,USB-C Charging Cable,1,1,11.95,11.95,February,2/1/2019 5:50,937 Jackson St,Dallas,TX,75001
4,159327,AAA Batteries (4-pack),1,1,2.99,2.99,February,2/1/2019 6:14,733 Chestnut St,Austin,TX,73301
...,...,...,...,...,...,...,...,...,...,...,...,...
11981,150533,AAA Batteries (4-pack),1,1,2.99,2.99,March,3/1/2019 3:06,270 Dogwood St,San Francisco,CA,94016
11982,159347,AAA Batteries (4-pack),1,1,2.99,2.99,March,3/1/2019 3:10,297 8th St,Austin,TX,73301
11983,153284,Wired Headphones,1,1,11.99,11.99,March,3/1/2019 3:47,38 Church St,Los Angeles,CA,90001
11984,158262,Wired Headphones,1,1,11.99,11.99,March,3/1/2019 3:49,902 Adams St,New York City,NY,10001
11985,152036,ThinkPad Laptop,1,1,999.99,999.99,March,3/1/2019 5:56,477 Washington St,San Francisco,CA,94016

In [ ]:
feb.describe()

,Order ID,lenth,Quantity Ordered,Price Each,Total of Amount,number of state
count,11986.000000,11986.0,11986.00000,11986.000000,11986.000000,11986.000000
mean,156250.613382,1.0,1.12306,182.741507,183.837914,64007.663608
std,3322.075263,0.0,0.43111,325.543296,325.589573,37738.476048
min,150502.000000,1.0,1.00000,2.990000,2.990000,2215.000000
25%,153374.250000,1.0,1.00000,11.950000,11.950000,10001.000000
50%,156247.500000,1.0,1.00000,14.950000,14.950000,90001.000000
75%,159123.750000,1.0,1.00000,150.000000,150.000000,94016.000000
max,162008.000000,1.0,7.00000,1700.000000,1700.000000,98101.000000

In [ ]:
feb.drop_duplicates()

,Order ID,Product,lenth,Quantity Ordered,Price Each,Total of Amount,Month,Order Date,Purchase Address,Country,State,number of state
0,160509,AAA Batteries (4-pack),1,2,2.99,5.98,February,2/1/2019 1:51,597 Chestnut St,Austin,TX,73301
1,156889,USB-C Charging Cable,1,1,11.95,11.95,February,2/1/2019 4:25,703 9th St,Los Angeles,CA,90001
2,156342,USB-C Charging Cable,1,1,11.95,11.95,February,2/1/2019 5:39,556 Cherry St,San Francisco,CA,94016
3,159193,USB-C Charging Cable,1,1,11.95,11.95,February,2/1/2019 5:50,937 Jackson St,Dallas,TX,75001
4,159327,AAA Batteries (4-pack),1,1,2.99,2.99,February,2/1/2019 6:14,733 Chestnut St,Austin,TX,73301
...,...,...,...,...,...,...,...,...,...,...,...,...
11981,150533,AAA Batteries (4-pack),1,1,2.99,2.99,March,3/1/2019 3:06,270 Dogwood St,San Francisco,CA,94016
11982,159347,AAA Batteries (4-pack),1,1,2.99,2.99,March,3/1/2019 3:10,297 8th St,Austin,TX,73301
11983,153284,Wired Headphones,1,1,11.99,11.99,March,3/1/2019 3:47,38 Church St,Los Angeles,CA,90001
11984,158262,Wired Headphones,1,1,11.99,11.99,March,3/1/2019 3:49,902 Adams St,New York City,NY,10001
11985,152036,ThinkPad Laptop,1,1,999.99,999.99,March,3/1/2019 5:56,477 Washington St,San Francisco,CA,94016

In [ ]:
feb.to_csv('feb1')

In [ ]:
jan = pd.read_csv('/content/Sales_January_2019.csv')

In [ ]:
jan

,Order ID,Product,lenth,Quantity Ordered,Price Each,Total,Order Date,Month,Purchase Address,Country,State,Number of state
0,141234,iPhone,1,1,700.00,700.00,1/22/2019 21:25,January,944 Walnut St,Boston,MA,2215
1,141235,Lightning Charging Cable,1,1,14.95,14.95,1/28/2019 14:15,January,185 Maple St,Portland,OR,97035
2,141236,Wired Headphones,1,2,11.99,23.98,1/17/2019 13:33,January,538 Adams St,San Francisco,CA,94016
3,141237,27in FHD Monitor,1,1,149.99,149.99,1/5/2019 20:33,January,738 10th St,Los Angeles,CA,90001
4,141238,Wired Headphones,1,1,11.99,11.99,1/25/2019 11:59,January,387 10th St,Austin,TX,73301
...,...,...,...,...,...,...,...,...,...,...,...,...
9676,150497,20in Monitor,1,1,109.99,109.99,1/26/2019 19:09,January,95 8th St,Dallas,TX,75001
9677,150498,27in FHD Monitor,1,1,149.99,149.99,1/10/2019 22:58,January,403 7th St,San Francisco,CA,94016
9678,150499,ThinkPad Laptop,1,1,999.99,999.99,1/21/2019 14:31,January,214 Main St,Portland,OR,97035
9679,150500,AAA Batteries (4-pack),1,2,2.99,5.98,1/15/2019 14:21,January,810 2nd St,Los Angeles,CA,90001
9680,150501,Google Phone,1,1,600.00,600.00,1/13/2019 16:43,January,428 Cedar St,Boston,MA,2215

In [ ]:
jan.isnull().sum()

Order ID            0
Product             0
lenth               0
Quantity Ordered    0
Price Each          0
Total               0
Order Date          0
Month               0
Purchase Address    0
Country             0
State               0
Number of state     0
dtype: int64

In [ ]:
jan.drop_duplicates()

NameError: ignored

In [ ]:
jan.to_csv('jan1')

In [ ]:
june = pd.read_csv('/content/Sales_June_2019.csv')

In [ ]:
june

,Order ID,Product,lenth,Quantity Ordered,Price Each,Total,Month,Order Date,Purchase Address,Country,State,Number of State
0,217932,Lightning Charging Cable,1,2,14.95,29.9,June,6/1/2019 4:52,653 Forest St,Atlanta,GA,30301.0
1,220585,Apple Airpods Headphones,1,1,150,150,June,6/1/2019 5:16,158 Dogwood St,New York City,NY,10001.0
2,209977,AA Batteries (4-pack),1,1,3.84,3.84,June,6/1/2019 6:28,96 14th St,Los Angeles,CA,90001.0
3,222469,iPhone,1,1,700,700,June,6/1/2019 6:37,633 Center St,New York City,NY,10001.0
4,222469,Lightning Charging Cable,1,1,14.95,14.95,June,6/1/2019 6:37,633 Center St,New York City,NY,10001.0
...,...,...,...,...,...,...,...,...,...,...,...,...
13284,Order ID,Product,16,Quantity Ordered,Price Each,#VALUE!,Order Date,Order Date,Purchase Address,NaN,NaN,NaN
13285,Order ID,Product,16,Quantity Ordered,Price Each,#VALUE!,Order Date,Order Date,Purchase Address,NaN,NaN,NaN
13286,Order ID,Product,16,Quantity Ordered,Price Each,#VALUE!,Order Date,Order Date,Purchase Address,NaN,NaN,NaN
13287,Order ID,Product,16,Quantity Ordered,Price Each,#VALUE!,Order Date,Order Date,Purchase Address,NaN,NaN,NaN
13288,Order ID,Product,16,Quantity Ordered,Price Each,#VALUE!,Order Date,Order Date,Purchase Address,NaN,NaN,NaN

In [ ]:
june.describe()

              lenth  Number of State
count  13289.000000     13266.000000
mean       1.025961     64269.945500
std        0.623518     37609.255923
min        1.000000      2215.000000
25%        1.000000     30301.000000
50%        1.000000     90001.000000
75%        1.000000     94016.000000
max       16.000000     98101.000000

In [ ]:
june.isnull().sum()

Order ID             0
Product              0
lenth                0
Quantity Ordered     0
Price Each           0
Total                0
Month                0
Order Date           0
Purchase Address     0
Country             23
State               23
Number of State     23
dtype: int64

In [ ]:
jun = june.dropna()

In [ ]:
jun.isnull().sum()

Order ID            0
Product             0
lenth               0
Quantity Ordered    0
Price Each          0
Total               0
Month               0
Order Date          0
Purchase Address    0
Country             0
State               0
Number of State     0
dtype: int64

In [ ]:
jun.drop_duplicates()

,Order ID,Product,lenth,Quantity Ordered,Price Each,Total,Month,Order Date,Purchase Address,Country,State,Number of State
0,217932,Lightning Charging Cable,1,2,14.95,29.9,June,6/1/2019 4:52,653 Forest St,Atlanta,GA,30301.0
1,220585,Apple Airpods Headphones,1,1,150,150,June,6/1/2019 5:16,158 Dogwood St,New York City,NY,10001.0
2,209977,AA Batteries (4-pack),1,1,3.84,3.84,June,6/1/2019 6:28,96 14th St,Los Angeles,CA,90001.0
3,222469,iPhone,1,1,700,700,June,6/1/2019 6:37,633 Center St,New York City,NY,10001.0
4,222469,Lightning Charging Cable,1,1,14.95,14.95,June,6/1/2019 6:37,633 Center St,New York City,NY,10001.0
...,...,...,...,...,...,...,...,...,...,...,...,...
13261,213660,USB-C Charging Cable,1,1,11.95,11.95,July,7/1/2019 2:06,505 Cherry St,San Francisco,CA,94016.0
13262,216431,Vareebadd Phone,1,1,400,400,July,7/1/2019 2:53,640 Cherry St,Dallas,TX,75001.0
13263,216431,Google Phone,1,1,600,600,July,7/1/2019 2:53,640 Cherry St,Dallas,TX,75001.0
13264,214986,Bose SoundSport Headphones,1,1,99.99,99.99,July,7/1/2019 2:59,877 Wilson St,Boston,MA,2215.0
13265,218457,27in 4K Gaming Monitor,1,1,389.99,389.99,July,7/1/2019 3:09,567 Forest St,San Francisco,CA,94016.0

In [ ]:
jun.to_csv('june')

In [ ]:
march = pd.read_csv('/content/Sales_March_2019.csv')

In [ ]:
march

,Order ID,Product,lenth,Quantity Ordered,Price Each,Total,Month,Order Date,Purchase Address,Country,State,Number of state
0,175045,USB-C Charging Cable,1,1,11.95,11.95,March,3/1/2019 3:15,233 Jefferson St,New York City,NY,10001
1,170411,Wired Headphones,1,1,11.99,11.99,March,3/1/2019 4:23,427 Wilson St,Los Angeles,CA,90001
2,171218,USB-C Charging Cable,1,1,11.95,11.95,March,3/1/2019 4:42,498 5th St,Austin,TX,73301
3,173057,iPhone,1,1,700.00,700.00,March,3/1/2019 5:40,256 1st St,Atlanta,GA,30301
4,165475,AA Batteries (4-pack),1,1,3.84,3.84,March,3/1/2019 5:41,344 1st St,San Francisco,CA,94016
...,...,...,...,...,...,...,...,...,...,...,...,...
15149,166309,AA Batteries (4-pack),1,1,3.84,3.84,April,4/1/2019 1:32,2 Church St,Seattle,WA,98101
15150,175769,Bose SoundSport Headphones,1,1,99.99,99.99,April,4/1/2019 2:22,974 13th St,New York City,NY,10001
15151,167813,27in 4K Gaming Monitor,1,1,389.99,389.99,April,4/1/2019 2:42,840 11th St,Seattle,WA,98101
15152,165622,Lightning Charging Cable,1,1,14.95,14.95,April,4/1/2019 2:59,65 Madison St,Boston,MA,2215
15153,174575,AA Batteries (4-pack),1,1,3.84,3.84,April,4/1/2019 3:21,969 Adams St,Boston,MA,2215

In [ ]:
  marc = march.drop_duplicates()

In [ ]:
marc

,Order ID,Product,lenth,Quantity Ordered,Price Each,Total,Month,Order Date,Purchase Address,Country,State,Number of state
0,175045,USB-C Charging Cable,1,1,11.95,11.95,March,3/1/2019 3:15,233 Jefferson St,New York City,NY,10001
1,170411,Wired Headphones,1,1,11.99,11.99,March,3/1/2019 4:23,427 Wilson St,Los Angeles,CA,90001
2,171218,USB-C Charging Cable,1,1,11.95,11.95,March,3/1/2019 4:42,498 5th St,Austin,TX,73301
3,173057,iPhone,1,1,700.00,700.00,March,3/1/2019 5:40,256 1st St,Atlanta,GA,30301
4,165475,AA Batteries (4-pack),1,1,3.84,3.84,March,3/1/2019 5:41,344 1st St,San Francisco,CA,94016
...,...,...,...,...,...,...,...,...,...,...,...,...
15149,166309,AA Batteries (4-pack),1,1,3.84,3.84,April,4/1/2019 1:32,2 Church St,Seattle,WA,98101
15150,175769,Bose SoundSport Headphones,1,1,99.99,99.99,April,4/1/2019 2:22,974 13th St,New York City,NY,10001
15151,167813,27in 4K Gaming Monitor,1,1,389.99,389.99,April,4/1/2019 2:42,840 11th St,Seattle,WA,98101
15152,165622,Lightning Charging Cable,1,1,14.95,14.95,April,4/1/2019 2:59,65 Madison St,Boston,MA,2215
15153,174575,AA Batteries (4-pack),1,1,3.84,3.84,April,4/1/2019 3:21,969 Adams St,Boston,MA,2215

In [ ]:
marc.to_csv('march')

In [ ]:
april = pd.read_csv('/content/Sales_April_2019.csv')

In [ ]:
april

,Order ID,Product,lengh,Quantity Ordered,Price Each,total Amount,Order Date,Month,Purchase Address,Country,State,Number of state
0,177831,Lightning Charging Cable,1,1,14.95,14.95,4/1/2019 3:09,April,914 6th St,San Francisco,CA,94016
1,177687,Wired Headphones,1,1,11.99,11.99,4/1/2019 4:12,April,23 Meadow St,San Francisco,CA,94016
2,186754,27in FHD Monitor,1,1,149.99,149.99,4/1/2019 5:06,April,824 Chestnut St,San Francisco,CA,94016
3,185103,USB-C Charging Cable,1,1,11.95,11.95,4/1/2019 5:18,April,610 Washington St,San Francisco,CA,94016
4,191585,20in Monitor,1,1,109.99,109.99,4/1/2019 5:58,April,686 Main St,New York City,NY,10001
...,...,...,...,...,...,...,...,...,...,...,...,...
18122,181688,ThinkPad Laptop,1,1,999.99,999.99,5/1/2019 2:07,May,123 4th St,San Francisco,CA,94016
18123,189854,USB-C Charging Cable,1,1,11.95,11.95,5/1/2019 2:09,May,743 Elm St,Boston,MA,2215
18124,181645,Apple Airpods Headphones,1,1,150.00,150.00,5/1/2019 2:37,May,514 2nd St,Los Angeles,CA,90001
18125,179134,Apple Airpods Headphones,1,1,150.00,150.00,5/1/2019 2:41,May,950 Church St,Los Angeles,CA,90001
18126,194067,iPhone,1,1,700.00,700.00,5/1/2019 4:25,May,291 North St,San Francisco,CA,94016

In [ ]:
  ap = april.drop_duplicates()

In [ ]:
ap

,Order ID,Product,lengh,Quantity Ordered,Price Each,total Amount,Order Date,Month,Purchase Address,Country,State,Number of state
0,177831,Lightning Charging Cable,1,1,14.95,14.95,4/1/2019 3:09,April,914 6th St,San Francisco,CA,94016
1,177687,Wired Headphones,1,1,11.99,11.99,4/1/2019 4:12,April,23 Meadow St,San Francisco,CA,94016
2,186754,27in FHD Monitor,1,1,149.99,149.99,4/1/2019 5:06,April,824 Chestnut St,San Francisco,CA,94016
3,185103,USB-C Charging Cable,1,1,11.95,11.95,4/1/2019 5:18,April,610 Washington St,San Francisco,CA,94016
4,191585,20in Monitor,1,1,109.99,109.99,4/1/2019 5:58,April,686 Main St,New York City,NY,10001
...,...,...,...,...,...,...,...,...,...,...,...,...
18122,181688,ThinkPad Laptop,1,1,999.99,999.99,5/1/2019 2:07,May,123 4th St,San Francisco,CA,94016
18123,189854,USB-C Charging Cable,1,1,11.95,11.95,5/1/2019 2:09,May,743 Elm St,Boston,MA,2215
18124,181645,Apple Airpods Headphones,1,1,150.00,150.00,5/1/2019 2:37,May,514 2nd St,Los Angeles,CA,90001
18125,179134,Apple Airpods Headphones,1,1,150.00,150.00,5/1/2019 2:41,May,950 Church St,Los Angeles,CA,90001
18126,194067,iPhone,1,1,700.00,700.00,5/1/2019 4:25,May,291 North St,San Francisco,CA,94016

In [ ]:
ap.to_csv('april')

In [ ]:
august  = pd.read_csv('/content/Sales_August_2019.csv')

In [ ]:
august

,Order ID,Product,Lenth,Quantity Ordered,Price Each,Total,Month,Order Date,Purchase Address,Country,State,Number of State
0,242859,27in 4K Gaming Monitor,1,1,389.99,389.99,August,8/1/2019 4:50,980 Dogwood St,San Francisco,CA,94016
1,240817,AA Batteries (4-pack),1,1,3.84,3.84,August,8/1/2019 5:13,463 1st St,San Francisco,CA,94016
2,243454,Lightning Charging Cable,1,1,14.95,14.95,August,8/1/2019 5:13,50 9th St,Los Angeles,CA,90001
3,241974,Wired Headphones,1,1,11.99,11.99,August,8/1/2019 5:48,386 Maple St,Los Angeles,CA,90001
4,240910,Flatscreen TV,1,1,300.00,300.00,August,8/1/2019 7:38,482 Washington St,San Francisco,CA,94016
...,...,...,...,...,...,...,...,...,...,...,...,...
5656,244953,Lightning Charging Cable,1,1,14.95,14.95,September,9/1/2019 0:26,262 Park St,Los Angeles,CA,90001
5657,243667,USB-C Charging Cable,1,1,11.95,11.95,September,9/1/2019 0:55,959 Center St,San Francisco,CA,94016
5658,242865,27in FHD Monitor,1,1,149.99,149.99,September,9/1/2019 1:28,678 Washington St,San Francisco,CA,94016
5659,240636,Lightning Charging Cable,1,1,14.95,14.95,September,9/1/2019 2:07,63 1st St,Seattle,WA,98101
5660,242343,ThinkPad Laptop,1,1,999.99,999.99,September,9/1/2019 2:44,510 Park St,Boston,MA,2215

In [ ]:
 aug= august.drop_duplicates()

In [ ]:
aug

,Order ID,Product,Lenth,Quantity Ordered,Price Each,Total,Month,Order Date,Purchase Address,Country,State,Number of State
0,242859,27in 4K Gaming Monitor,1,1,389.99,389.99,August,8/1/2019 4:50,980 Dogwood St,San Francisco,CA,94016
1,240817,AA Batteries (4-pack),1,1,3.84,3.84,August,8/1/2019 5:13,463 1st St,San Francisco,CA,94016
2,243454,Lightning Charging Cable,1,1,14.95,14.95,August,8/1/2019 5:13,50 9th St,Los Angeles,CA,90001
3,241974,Wired Headphones,1,1,11.99,11.99,August,8/1/2019 5:48,386 Maple St,Los Angeles,CA,90001
4,240910,Flatscreen TV,1,1,300.00,300.00,August,8/1/2019 7:38,482 Washington St,San Francisco,CA,94016
...,...,...,...,...,...,...,...,...,...,...,...,...
5656,244953,Lightning Charging Cable,1,1,14.95,14.95,September,9/1/2019 0:26,262 Park St,Los Angeles,CA,90001
5657,243667,USB-C Charging Cable,1,1,11.95,11.95,September,9/1/2019 0:55,959 Center St,San Francisco,CA,94016
5658,242865,27in FHD Monitor,1,1,149.99,149.99,September,9/1/2019 1:28,678 Washington St,San Francisco,CA,94016
5659,240636,Lightning Charging Cable,1,1,14.95,14.95,September,9/1/2019 2:07,63 1st St,Seattle,WA,98101
5660,242343,ThinkPad Laptop,1,1,999.99,999.99,September,9/1/2019 2:44,510 Park St,Boston,MA,2215

In [ ]:
aug.to_csv('august')

In [ ]:
sept = pd.read_csv('/content/Sales_September_2019.csv')

In [ ]:
sept

,Order ID,Product,Lenth,Quantity Ordered,Price Each,Total,Month,Order Date,Purchase Address,Country,State,Number of State
0,248922,Apple Airpods Headphones,1,1,150.00,150.00,September,9/1/2019 5:10,39 Spruce St,Portland,ME,4101
1,258065,AA Batteries (4-pack),1,4,3.84,15.36,September,9/1/2019 6:08,752 Meadow St,San Francisco,CA,94016
2,257173,USB-C Charging Cable,1,1,11.95,11.95,September,9/1/2019 6:09,9 1st St,San Francisco,CA,94016
3,251424,20in Monitor,1,1,109.99,109.99,September,9/1/2019 6:14,649 Sunset St,Portland,OR,97035
4,248401,27in FHD Monitor,1,1,149.99,149.99,September,9/1/2019 6:40,514 6th St,Seattle,WA,98101
...,...,...,...,...,...,...,...,...,...,...,...,...
11624,255614,Bose SoundSport Headphones,1,1,99.99,99.99,October,10/1/2019 2:18,181 4th St,Los Angeles,CA,90001
11625,259228,AA Batteries (4-pack),1,1,3.84,3.84,October,10/1/2019 2:55,71 2nd St,Los Angeles,CA,90001
11626,257017,AAA Batteries (4-pack),1,3,2.99,8.97,October,10/1/2019 3:14,545 Washington St,San Francisco,CA,94016
11627,250684,AAA Batteries (4-pack),1,1,2.99,2.99,October,10/1/2019 3:38,985 Pine St,San Francisco,CA,94016
11628,253168,20in Monitor,1,1,109.99,109.99,October,10/1/2019 4:06,105 Sunset St,Boston,MA,2215

In [ ]:
  sep = sept.drop_duplicates()

In [ ]:
sep

,Order ID,Product,Lenth,Quantity Ordered,Price Each,Total,Month,Order Date,Purchase Address,Country,State,Number of State
0,248922,Apple Airpods Headphones,1,1,150.00,150.00,September,9/1/2019 5:10,39 Spruce St,Portland,ME,4101
1,258065,AA Batteries (4-pack),1,4,3.84,15.36,September,9/1/2019 6:08,752 Meadow St,San Francisco,CA,94016
2,257173,USB-C Charging Cable,1,1,11.95,11.95,September,9/1/2019 6:09,9 1st St,San Francisco,CA,94016
3,251424,20in Monitor,1,1,109.99,109.99,September,9/1/2019 6:14,649 Sunset St,Portland,OR,97035
4,248401,27in FHD Monitor,1,1,149.99,149.99,September,9/1/2019 6:40,514 6th St,Seattle,WA,98101
...,...,...,...,...,...,...,...,...,...,...,...,...
11624,255614,Bose SoundSport Headphones,1,1,99.99,99.99,October,10/1/2019 2:18,181 4th St,Los Angeles,CA,90001
11625,259228,AA Batteries (4-pack),1,1,3.84,3.84,October,10/1/2019 2:55,71 2nd St,Los Angeles,CA,90001
11626,257017,AAA Batteries (4-pack),1,3,2.99,8.97,October,10/1/2019 3:14,545 Washington St,San Francisco,CA,94016
11627,250684,AAA Batteries (4-pack),1,1,2.99,2.99,October,10/1/2019 3:38,985 Pine St,San Francisco,CA,94016
11628,253168,20in Monitor,1,1,109.99,109.99,October,10/1/2019 4:06,105 Sunset St,Boston,MA,2215

In [ ]:
sep.to_csv('sept')

In [ ]:
octo = pd.read_csv('/content/Sales_October_2019.csv')

In [ ]:
octo

,Order ID,Product,Lenth,Quantity Ordered,Price Each,Total,Month,Order Date,Purchase Address,Country,State,Number of State
0,269590,ThinkPad Laptop,1,1,999.99,999.99,October,10/1/2019 3:12,907 2nd St,Los Angeles,CA,90001
1,269164,20in Monitor,1,1,109.99,109.99,October,10/1/2019 4:24,856 13th St,New York City,NY,10001
2,264038,Wired Headphones,1,1,11.99,11.99,October,10/1/2019 5:01,347 4th St,Los Angeles,CA,90001
3,276847,AAA Batteries (4-pack),1,4,2.99,11.96,October,10/1/2019 5:03,907 Meadow St,Portland,OR,97035
4,276847,Wired Headphones,1,2,11.99,23.98,October,10/1/2019 5:03,907 Meadow St,Portland,OR,97035
...,...,...,...,...,...,...,...,...,...,...,...,...
20279,273655,Apple Airpods Headphones,1,1,150.00,150.00,November,11/1/2019 1:58,313 Jefferson St,New York City,NY,10001
20280,268081,Bose SoundSport Headphones,1,1,99.99,99.99,November,11/1/2019 2:15,140 13th St,Atlanta,GA,30301
20281,277647,27in 4K Gaming Monitor,1,1,389.99,389.99,November,11/1/2019 2:15,72 River St,Boston,MA,2215
20282,262928,Lightning Charging Cable,1,1,14.95,14.95,November,11/1/2019 2:33,89 4th St,New York City,NY,10001
20283,275546,USB-C Charging Cable,1,2,11.95,23.90,November,11/1/2019 2:38,571 North St,Seattle,WA,98101

In [ ]:
  oct = octo.drop_duplicates()

In [ ]:
oct

,Order ID,Product,Lenth,Quantity Ordered,Price Each,Total,Month,Order Date,Purchase Address,Country,State,Number of State
0,269590,ThinkPad Laptop,1,1,999.99,999.99,October,10/1/2019 3:12,907 2nd St,Los Angeles,CA,90001
1,269164,20in Monitor,1,1,109.99,109.99,October,10/1/2019 4:24,856 13th St,New York City,NY,10001
2,264038,Wired Headphones,1,1,11.99,11.99,October,10/1/2019 5:01,347 4th St,Los Angeles,CA,90001
3,276847,AAA Batteries (4-pack),1,4,2.99,11.96,October,10/1/2019 5:03,907 Meadow St,Portland,OR,97035
4,276847,Wired Headphones,1,2,11.99,23.98,October,10/1/2019 5:03,907 Meadow St,Portland,OR,97035
...,...,...,...,...,...,...,...,...,...,...,...,...
20279,273655,Apple Airpods Headphones,1,1,150.00,150.00,November,11/1/2019 1:58,313 Jefferson St,New York City,NY,10001
20280,268081,Bose SoundSport Headphones,1,1,99.99,99.99,November,11/1/2019 2:15,140 13th St,Atlanta,GA,30301
20281,277647,27in 4K Gaming Monitor,1,1,389.99,389.99,November,11/1/2019 2:15,72 River St,Boston,MA,2215
20282,262928,Lightning Charging Cable,1,1,14.95,14.95,November,11/1/2019 2:33,89 4th St,New York City,NY,10001
20283,275546,USB-C Charging Cable,1,2,11.95,23.90,November,11/1/2019 2:38,571 North St,Seattle,WA,98101

In [ ]:
oct.to_csv('october')

In [ ]:
nove = pd.read_csv('/content/Sales_November_2019.csv')

In [ ]:
nove

,Order ID,Product,Lenth,Quantity Ordered,Price Each,Total,Order Date,Month,Purchase Address,Country,State,code
0,292700,AAA Batteries (4-pack),1,2,2.99,5.98,11/1/2019 3:18,November,586 Ridge St,New York City,NY,10001
1,292205,27in FHD Monitor,1,1,149.99,149.99,11/1/2019 3:50,November,123 Johnson St,Boston,MA,2215
2,285738,Lightning Charging Cable,1,1,14.95,14.95,11/1/2019 5:40,November,551 Hickory St,San Francisco,CA,94016
3,283900,USB-C Charging Cable,1,1,11.95,11.95,11/1/2019 6:06,November,97 Walnut St,Seattle,WA,98101
4,295315,iPhone,1,1,700.00,700.00,11/1/2019 6:18,November,774 4th St,Atlanta,GA,30301
...,...,...,...,...,...,...,...,...,...,...,...,...
16031,294629,Wired Headphones,1,1,11.99,11.99,12/1/2019 1:54,NaN,668 Ridge St,San Francisco,CA,94016
16032,293713,Apple Airpods Headphones,1,1,150.00,150.00,12/1/2019 2:30,NaN,684 14th St,New York City,NY,10001
16033,280809,Lightning Charging Cable,1,1,14.95,14.95,12/1/2019 2:33,NaN,368 7th St,Dallas,TX,75001
16034,293658,Lightning Charging Cable,1,1,14.95,14.95,12/1/2019 2:44,NaN,934 Lincoln St,Dallas,TX,75001
16035,283689,AAA Batteries (4-pack),1,1,2.99,2.99,12/1/2019 3:28,NaN,848 Walnut St,San Francisco,CA,94016

In [ ]:
nove.isnull().sum()

Order ID                0
Product                 0
Lenth                   0
Quantity Ordered        0
Price Each              0
Total                   0
Order Date              0
Month               15798
Purchase Address        0
Country                 0
State                   0
code                    0
dtype: int64

In [ ]:
novee = nove.dropna()

In [ ]:
novee

,Order ID,Product,Lenth,Quantity Ordered,Price Each,Total,Order Date,Month,Purchase Address,Country,State,code
0,292700,AAA Batteries (4-pack),1,2,2.99,5.98,11/1/2019 3:18,November,586 Ridge St,New York City,NY,10001
1,292205,27in FHD Monitor,1,1,149.99,149.99,11/1/2019 3:50,November,123 Johnson St,Boston,MA,2215
2,285738,Lightning Charging Cable,1,1,14.95,14.95,11/1/2019 5:40,November,551 Hickory St,San Francisco,CA,94016
3,283900,USB-C Charging Cable,1,1,11.95,11.95,11/1/2019 6:06,November,97 Walnut St,Seattle,WA,98101
4,295315,iPhone,1,1,700.00,700.00,11/1/2019 6:18,November,774 4th St,Atlanta,GA,30301
...,...,...,...,...,...,...,...,...,...,...,...,...
14007,278805,Lightning Charging Cable,1,1,14.95,14.95,11/27/2019 11:50,November,670 Elm St,San Francisco,NY,10001
14476,278841,USB-C Charging Cable,1,1,11.95,11.95,11/28/2019 9:07,November,847 Dogwood St,San Francisco,NY,10001
15369,278823,AA Batteries (4-pack),1,1,3.84,3.84,11/29/2019 20:42,November,234 9th St,Boston,NY,10001
15743,278857,USB-C Charging Cable,1,1,11.95,11.95,11/30/2019 15:37,November,150 Wilson St,Los Angeles,NY,10001
15744,278857,AAA Batteries (4-pack),1,2,2.99,5.98,11/30/2019 15:37,November,150 Wilson St,Los Angeles,NY,10001

In [ ]:
  nov = novee.drop_duplicates()

In [ ]:
nov

,Order ID,Product,Lenth,Quantity Ordered,Price Each,Total,Order Date,Month,Purchase Address,Country,State,code
0,292700,AAA Batteries (4-pack),1,2,2.99,5.98,11/1/2019 3:18,November,586 Ridge St,New York City,NY,10001
1,292205,27in FHD Monitor,1,1,149.99,149.99,11/1/2019 3:50,November,123 Johnson St,Boston,MA,2215
2,285738,Lightning Charging Cable,1,1,14.95,14.95,11/1/2019 5:40,November,551 Hickory St,San Francisco,CA,94016
3,283900,USB-C Charging Cable,1,1,11.95,11.95,11/1/2019 6:06,November,97 Walnut St,Seattle,WA,98101
4,295315,iPhone,1,1,700.00,700.00,11/1/2019 6:18,November,774 4th St,Atlanta,GA,30301
...,...,...,...,...,...,...,...,...,...,...,...,...
14007,278805,Lightning Charging Cable,1,1,14.95,14.95,11/27/2019 11:50,November,670 Elm St,San Francisco,NY,10001
14476,278841,USB-C Charging Cable,1,1,11.95,11.95,11/28/2019 9:07,November,847 Dogwood St,San Francisco,NY,10001
15369,278823,AA Batteries (4-pack),1,1,3.84,3.84,11/29/2019 20:42,November,234 9th St,Boston,NY,10001
15743,278857,USB-C Charging Cable,1,1,11.95,11.95,11/30/2019 15:37,November,150 Wilson St,Los Angeles,NY,10001
15744,278857,AAA Batteries (4-pack),1,2,2.99,5.98,11/30/2019 15:37,November,150 Wilson St,Los Angeles,NY,10001

In [ ]:
nov.to_csv('novv')

In [ ]:
dece = pd.read_csv('/content/Sales_December_2019.csv')

In [ ]:
dece

,Order ID,Product,Lenth,Quantity Ordered,Price Each,Total,Month,Order Date,Purchase Address,Country,State,Number of State
0,301778,USB-C Charging Cable,1,1,11.95,11.95,December,12/1/2019 2:50,920 Highland St,Seattle,WA,98101
1,309213,Google Phone,1,1,600.00,600.00,December,12/1/2019 3:10,694 11th St,Portland,OR,97035
2,314587,34in Ultrawide Monitor,1,1,379.99,379.99,December,12/1/2019 4:06,746 North St,Dallas,TX,75001
3,315501,Wired Headphones,1,1,11.99,11.99,December,12/1/2019 4:10,588 Lincoln St,Boston,MA,2215
4,312424,AAA Batteries (4-pack),1,1,2.99,2.99,December,12/1/2019 4:24,226 Elm St,New York City,NY,10001
...,...,...,...,...,...,...,...,...,...,...,...,...
24950,297481,AA Batteries (4-pack),1,1,3.84,3.84,December,12/31/2019 23:42,82 Hill St,Dallas,TX,75001
24951,298406,AAA Batteries (4-pack),1,2,2.99,5.98,December,12/31/2019 23:42,30 Elm St,San Francisco,CA,94016
24952,317048,AAA Batteries (4-pack),1,2,2.99,5.98,December,12/31/2019 23:45,743 Adams St,San Francisco,CA,94016
24953,309773,AAA Batteries (4-pack),1,1,2.99,2.99,December,12/31/2019 23:52,60 Hickory St,Los Angeles,CA,90001
24954,297674,AAA Batteries (4-pack),1,1,2.99,2.99,December,12/31/2019 23:53,425 Lake St,Portland,OR,97035

In [ ]:
  dec = dece.drop_duplicates()

In [ ]:
dec

,Order ID,Product,Lenth,Quantity Ordered,Price Each,Total,Month,Order Date,Purchase Address,Country,State,Number of State
0,301778,USB-C Charging Cable,1,1,11.95,11.95,December,12/1/2019 2:50,920 Highland St,Seattle,WA,98101
1,309213,Google Phone,1,1,600.00,600.00,December,12/1/2019 3:10,694 11th St,Portland,OR,97035
2,314587,34in Ultrawide Monitor,1,1,379.99,379.99,December,12/1/2019 4:06,746 North St,Dallas,TX,75001
3,315501,Wired Headphones,1,1,11.99,11.99,December,12/1/2019 4:10,588 Lincoln St,Boston,MA,2215
4,312424,AAA Batteries (4-pack),1,1,2.99,2.99,December,12/1/2019 4:24,226 Elm St,New York City,NY,10001
...,...,...,...,...,...,...,...,...,...,...,...,...
24950,297481,AA Batteries (4-pack),1,1,3.84,3.84,December,12/31/2019 23:42,82 Hill St,Dallas,TX,75001
24951,298406,AAA Batteries (4-pack),1,2,2.99,5.98,December,12/31/2019 23:42,30 Elm St,San Francisco,CA,94016
24952,317048,AAA Batteries (4-pack),1,2,2.99,5.98,December,12/31/2019 23:45,743 Adams St,San Francisco,CA,94016
24953,309773,AAA Batteries (4-pack),1,1,2.99,2.99,December,12/31/2019 23:52,60 Hickory St,Los Angeles,CA,90001
24954,297674,AAA Batteries (4-pack),1,1,2.99,2.99,December,12/31/2019 23:53,425 Lake St,Portland,OR,97035

In [ ]:
dec.to_csv('dec')

In [ ]:
july = pd.read_csv('/content/Sales_July_2019.csv')

In [ ]:
july

,Order ID,Product,lenth,Quantity Ordered,Price Each,Total,Month,Order Date,Purchase Address,Country,State,Number of State,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,223058,Bose SoundSport Headphones,1.0,1,99.99,99.99,July,7/1/2019 8:09,993 Main St,Boston,MA,2215.0,NaN,NaN,NaN,NaN
1,223043,Lightning Charging Cable,1.0,1,14.95,14.95,July,7/1/2019 10:20,662 North St,Atlanta,GA,30301.0,NaN,NaN,NaN,NaN
2,223093,AA Batteries (4-pack),1.0,1,3.84,3.84,July,7/1/2019 10:48,899 1st St,San Francisco,CA,94016.0,NaN,NaN,NaN,NaN
3,222955,USB-C Charging Cable,1.0,1,11.95,11.95,July,7/1/2019 14:27,117 Lake St,Los Angeles,CA,90001.0,NaN,NaN,NaN,NaN
4,223023,Bose SoundSport Headphones,1.0,1,99.99,99.99,July,7/1/2019 18:12,268 Meadow St,San Francisco,CA,94016.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14366,236665,Wired Headphones,NaN,1,11.99,NaN,NaN,7/20/2019 16:16,694 Meadow St,Atlanta,GA,30301.0,NaN,NaN,NaN,NaN
14367,236666,20in Monitor,NaN,1,109.99,NaN,NaN,7/31/2019 20:11,866 14th St,San Francisco,CA,94016.0,NaN,NaN,NaN,NaN
14368,236667,AAA Batteries (4-pack),NaN,1,2.99,NaN,NaN,7/17/2019 22:29,249 Cherry St,Dallas,TX,75001.0,NaN,NaN,NaN,NaN
14369,236668,Wired Headphones,NaN,1,11.99,NaN,NaN,7/30/2019 19:28,727 Wilson St,Austin,TX,73301.0,NaN,NaN,NaN,NaN
14370,236669,AAA Batteries (4-pack),NaN,1,2.99,NaN,NaN,7/10/2019 1:50,743 9th St,New York City,NY,10001.0,NaN,NaN,NaN,NaN

In [ ]:
july.isnull().sum()

Order ID               45
Product                45
lenth               14172
Quantity Ordered       45
Price Each             45
Total               14172
Month               14172
Order Date             45
Purchase Address       45
Country                80
State                  80
Number of State        80
Unnamed: 12         14371
Unnamed: 13         14371
Unnamed: 14         14371
Unnamed: 15         14371
dtype: int64

In [ ]:
  julyyy = july.drop_duplicates()

In [ ]:
julyyy

,Order ID,Product,lenth,Quantity Ordered,Price Each,Total,Month,Order Date,Purchase Address,Country,State,Number of State,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,223058,Bose SoundSport Headphones,1.0,1,99.99,99.99,July,7/1/2019 8:09,993 Main St,Boston,MA,2215.0,NaN,NaN,NaN,NaN
1,223043,Lightning Charging Cable,1.0,1,14.95,14.95,July,7/1/2019 10:20,662 North St,Atlanta,GA,30301.0,NaN,NaN,NaN,NaN
2,223093,AA Batteries (4-pack),1.0,1,3.84,3.84,July,7/1/2019 10:48,899 1st St,San Francisco,CA,94016.0,NaN,NaN,NaN,NaN
3,222955,USB-C Charging Cable,1.0,1,11.95,11.95,July,7/1/2019 14:27,117 Lake St,Los Angeles,CA,90001.0,NaN,NaN,NaN,NaN
4,223023,Bose SoundSport Headphones,1.0,1,99.99,99.99,July,7/1/2019 18:12,268 Meadow St,San Francisco,CA,94016.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14366,236665,Wired Headphones,NaN,1,11.99,NaN,NaN,7/20/2019 16:16,694 Meadow St,Atlanta,GA,30301.0,NaN,NaN,NaN,NaN
14367,236666,20in Monitor,NaN,1,109.99,NaN,NaN,7/31/2019 20:11,866 14th St,San Francisco,CA,94016.0,NaN,NaN,NaN,NaN
14368,236667,AAA Batteries (4-pack),NaN,1,2.99,NaN,NaN,7/17/2019 22:29,249 Cherry St,Dallas,TX,75001.0,NaN,NaN,NaN,NaN
14369,236668,Wired Headphones,NaN,1,11.99,NaN,NaN,7/30/2019 19:28,727 Wilson St,Austin,TX,73301.0,NaN,NaN,NaN,NaN
14370,236669,AAA Batteries (4-pack),NaN,1,2.99,NaN,NaN,7/10/2019 1:50,743 9th St,New York City,NY,10001.0,NaN,NaN,NaN,NaN

In [ ]:
julyyyy = julyyy.dropna()

In [ ]:
julyyyy

Empty DataFrame
Columns: [Order ID, Product, lenth, Quantity Ordered, Price Each, Total, Month, Order Date, Purchase Address, Country, State, Number of State, Unnamed: 12, Unnamed: 13, Unnamed: 14, Unnamed: 15]
Index: []

In [ ]:
jull

Empty DataFrame
Columns: [Order ID, Product, lenth, Quantity Ordered, Price Each, Total, Month, Order Date, Purchase Address, Country, State, Number of State, Unnamed: 12, Unnamed: 13, Unnamed: 14, Unnamed: 15]
Index: []